### ISSUE TITLE
Uncaught Error: Cannot find module 'classnames'

### ISSUE THREAD

**Issue by emillaine** [KochiyaOcean/electron-react-titlebar#13]
I get the following error when importing electron-react-titlebar:

```
Uncaught Error: Cannot find module 'classnames'
```

I believe the `classnames` package should be moved from devDependencies to dependencies to fix this.

**Comment by KochiyaOcean** [comment]
fixed by https://github.com/KochiyaOcean/electron-react-titlebar/commit/f2e7235031fb69ea56e957f9164a3932ddd50337
