### ISSUE TITLE
Incompatible with electron 14

### ISSUE THREAD

**Issue by vraravam** [KochiyaOcean/electron-react-titlebar#21]
Thanks for the useful library. Unfortunately, we are unable to upgrade to electron-14 due to the following bug. This appears in our console.
`Uncaught TypeError: Cannot read properties of undefined (reading 'getCurrentWindow')`

The error appears to occur here: `electron-react-titlebar/lib/window-controls.js:78` according to the firebug console.

We are using `0.8.2` of this package.

If you have a fix, I would be glad to test it out in our codebase. TIA!

**Comment by KochiyaOcean** [comment]
It's due to electron has removed remote module since 14. I'll try to find a solution to workaround with, but it might be a breaking change

**Comment by vraravam** [comment]
In [this line](https://github.com/KochiyaOcean/electron-react-titlebar/blob/93667543f6e9d381004da4bdfc9f90aab85f0c98/src/window-controls.js#L12) if you can make it `null`, and all over the code, if that value is set, then use it, that might be enough to unblock me. TIA

**Comment by KochiyaOcean** [comment]
Hello, I've published the new version `v1.0.0` and the issue should be resolved. Please have a try and tell me if you feel there is somewhere needs improvements.

**Comment by vraravam** [comment]
hi @KochiyaOcean - thanks for the quick response. I tried with v1.0.0, but this is the error that I now get:
```
No "exports" main defined in xxxxx/ferdi/node_modules/electron-react-titlebar/package.json
```

I have followed the instructions in the README, and my commit is [here](https://github.com/vraravam/ferdi/commit/69d02f054273d0d98e2f70ae1c15a5b67b726675)

**Comment by KochiyaOcean** [comment]
@vraravam You also need to change the import path in renderer process, which should be changed to `electron-react-titlebar/renderer`

**Comment by vraravam** [comment]
Thanks @KochiyaOcean - that fixed it!!! 🎉
