### ISSUE TITLE
1.2.0 package on npm contains outdated bundled files

### ISSUE THREAD

**Issue by kris7t** [KochiyaOcean/electron-react-titlebar#27]
When installing `electron-react-titlebar@1.2.0` from npm, the `dist` directory of the installed package contains a reference to `react-virtualized`, while all such references were removed from `src` in https://github.com/KochiyaOcean/electron-react-titlebar/commit/c01ae646bcdc81fe7df64da15a96a072140c8263.

```
$ npm i electron-react-titlebar@1.2.0

added 12 packages, and audited 13 packages in 701ms

found 0 vulnerabilities
$ rg --count-matches react-virtualized node_modules/electron-react-titlebar/src
$ rg --count-matches react-virtualized node_modules/electron-react-titlebar/dist
node_modules/electron-react-titlebar/dist/renderer.js.map:3
node_modules/electron-react-titlebar/dist/renderer.js:1

```

I suspect a version of the package with outdated bundle files was accidentally uploaded to npm.

This affects people who import `'electron-react-titlebar/renderer'` directly, because the bundle tries to access a(n outdated) dependency that is no longer referenced in `package.json`.

I suggest the npm package to be updated (with a version bump like 1.2.1) to distribute the up-to-date bundles.

**Comment by KochiyaOcean** [comment]
Thanks for report, I think the reason is that the `prepublish` script has already been deprecated by npm, so the package aren't built before publish

**Comment by vraravam** [comment]
Could you also please make a new release soon with the above fix?

**Comment by kris7t** [comment]
@KochiyaOcean Thanks for the super quick response! :heart: 

@vraravam 1.2.1 is already out now and it's working great for me.
