### ISSUE TITLE
Error using electron-react-titlebar

### ISSUE THREAD

**Issue by omarshehab221** [KochiyaOcean/electron-react-titlebar#7]
When I use electron-react-titlebar I get this error
in this file D:\Electron\test\node_modules\electron-react-titlebar\assets\style.css:1
Uncaught SyntaxError: Invalid or unexpected token
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Electron\test\node_modules\electron-compile\lib\require-hook.js:77:14)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at file:///D:/Electron/test/app/MainWindow/HTML/main.html:26:1

I am using the code mentioned [here](https://www.npmjs.com/package/electron-react-titlebar) with some edits
```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { TitleBar } from 'electron-react-titlebar';
import 'electron-react-titlebar/assets/style.css';

var template = [
    {
        label: "Menu 1",
         submenu: [
             {
                 label: "Item 1",
                 click: function() {
                     console.log("Menu 1 Item 1 clicked")
                 }
             },
             {
                 label: "Item 2",
                 click: function() {
                     console.log("Menu 1 Item 2 clicked")
                 }
             }
         ]
    },
    {
        label: "Menu 2",
        submenu: [
            {
                label: "Item 1",
                click: function() {
                    console.log("Menu 2 Item 1 clicked")
                }
            },
            {
                label: "Item 2",
                click: function() {
                    console.log("Menu 2 Item 2 clicked")
                }
            }
        ]
    }
]

ReactDOM.render(
    <TitleBar menu={template} icon={"./test.png"} disableMaximize={true} />,
    document.body
)
```

**Comment by KochiyaOcean** [comment]
Import css syntax requires webpack and css loader.

If you're not a webpack user, you can use `<link>` tag to load css.
Here is an example
```js
ReactDOM.render(
    <TitleBar menu={template} icon={"./test.png"} disableMaximize={true}>
      <link rel="stylesheet" type="text/css" href={require.resolve('electron-react-titlebar/assets/style.css')} />
    </TitleBar>,
    document.body
)
```

**Comment by omarshehab221** [comment]
Thank you vary much
and It looks great
